<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsValidLink" Id="{eac2773c-30ae-0cc3-3642-973a7d951e52}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidLink : BOOL
VAR_INPUT
	Link : I_Link;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidLink := Link <> 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>