<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsValidError" Id="{61028a02-7c42-0da0-1a47-e1d1d989ef56}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidError : BOOL
VAR_INPUT
	Error : I_Error;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidError := Error <> 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>