<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsValidInputPort" Id="{1ee37e81-2a18-025e-2a8e-aaa7ade41a36}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidInputPort : BOOL
VAR_INPUT
	InputPort : I_InputPort;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidInputPort := InputPort <> 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>