<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsValidProperty" Id="{f27cfd1a-d935-0531-0f17-a6712ace4c45}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidProperty : BOOL
VAR_INPUT
	PropertyToCheck : I_Property;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidProperty := PropertyToCheck <> 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>