<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="NodeFactory" Id="{04da50a7-58de-036b-3757-8d6436b4271f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT NodeFactory IMPLEMENTS I_NodeFactory
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Create" Id="{97d4ac09-63ea-06ec-3b31-d3c7623c5067}">
      <Declaration><![CDATA[METHOD ABSTRACT Create : I_Node]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>