<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="DisposableCollection" Id="{9e36cdcd-88ef-0310-24de-60899e6124c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DisposableCollection
VAR
	disposables : Stack;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="DisposeAndRemoveAll" Id="{318a25c1-4b89-0c0c-1ef1-19f5407dc5ec}">
      <Declaration><![CDATA[METHOD PUBLIC DisposeAndRemoveAll
VAR
	disposable : I_Disposable;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[WHILE disposables.TryPop(disposable) DO
	disposable.Dispose();
END_WHILE]]></ST>
      </Implementation>
    </Method>
    <Method Name="Insert" Id="{4ccca891-6202-09f4-1725-910f5f09648c}">
      <Declaration><![CDATA[METHOD PUBLIC Insert
VAR_INPUT
	DisposableToInsert : I_Disposable;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[disposables.Push(DisposableToInsert);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>