<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="InputPort_Trigger" Id="{c02d3224-6f96-0f96-1fe9-600e6363abf5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK InputPort_Trigger EXTENDS InputPort_ANY implements I_TriggerPort
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Result" Id="{e576605c-d71f-09ed-3b63-61daa81508ae}">
      <Declaration><![CDATA[PROPERTY PUBLIC Result : HRESULT]]></Declaration>
      <Get Name="Get" Id="{b83faf8c-762a-07b7-167e-c1a16ae1bf48}">
        <Declaration><![CDATA[VAR
	hresult : HRESULT;
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Get(hresult);
Result := hresult;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>