<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="NodeFactory_Display_BOOL" Id="{5cad8499-d6c8-0118-1afc-cd1bcbf5b9ae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK NodeFactory_Display_BOOL EXTENDS NodeFactory]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Create" Id="{033e8683-3b32-0af1-3303-11473673c1cc}">
      <Declaration><![CDATA[METHOD PUBLIC Create : I_Node
VAR
	pointerToNode : POINTER TO Node_Display_BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[pointerToNode := __NEW(Node_Display_BOOL);
Create := pointerToNode^;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>