<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PlcBasicNodePack" Id="{b1a7208c-fa6a-0ca2-104f-e5f6ddafa07d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PlcBasicNodePack IMPLEMENTS I_NodePack
VAR
	booleanLiteralNode : BooleanLiteralNode;
	booleanDisplayNode : BooleanDisplayNode;
	intLiteralNode : IntLiteralNode;
	intDisplayNode : IntDisplayNode;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RegisterWithNodeFactory" Id="{0a02d7c4-cf60-03c2-1373-451ec20f4e0e}">
      <Declaration><![CDATA[METHOD PUBLIC RegisterWithNodeFactory
VAR_INPUT
	NodeFactory : I_NodeFactory;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[NodeFactory.AddNodeAsPrototype('PlcBasic.Bool.BoolLiteral',booleanLiteralNode);
NodeFactory.AddNodeAsPrototype('PlcBasic.Bool.BoolDisplay',booleanDisplayNode);
NodeFactory.AddNodeAsPrototype('PlcBasic.Int.IntLiteral',intLiteralNode);
NodeFactory.AddNodeAsPrototype('PlcBasic.Int.IntDisplay',intDisplayNode);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>