<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="NodePack_PlcBasicLiterals" Id="{09b91d76-6524-009b-0de9-751b027e358a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK NodePack_PlcBasicLiterals IMPLEMENTS I_NodePack
VAR
	node_Literal_BOOL : Node_Literal_BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RegisterWithNodePrototypes" Id="{3ef8db7d-47fb-090b-3597-c30640cd5056}">
      <Declaration><![CDATA[METHOD PUBLIC RegisterWithNodePrototypes
VAR_INPUT
	NodePrototypes : I_NodePrototypes;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[NodePrototypes.RegisterNodeByType('PLC Basic/Literals/BOOL',node_Literal_BOOL);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>